version: "4"
services:
  API:
    image: api
    build:
      context: ./API
    ports:
      - "5000:5000"
    depends_on:
      - DB
  frontend:
    image: frontend
    build:
      context: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - API
  DB:
    image: mongo:latest
    container_name: mongohost
    command: mongod --port 27017
    ports:
      - "27017:27017"
